### ISSUE TITLE
Знайти місце проведення

### ISSUE THREAD

**Issue by Solomiya99** [Solomiya99/-sekta#1]
На 15 осіб
Поблизу центру міста

**Comment by Solomiya99** [comment]
В кого які пропозиції?

**Comment by mariyasafyanyk** [comment]
давайте "Криївка"

**Comment by systemofdown** [comment]
Старгород?

**Comment by vikaomelchenko** [comment]
Та ні, краще кафе "Штука"

**Comment by Solomiya99** [comment]
Надішліть фото бенкетного залу, будь ласка

**Comment by tushnitska** [comment]
Можливо "Centaur"? Поблизу Домініканського собору?

**Comment by mariyasafyanyk** [comment]
![image](https://user-images.githubusercontent.com/38327045/39178168-bfe76e90-47b9-11e8-8135-c7487ff6181e.png)

**Comment by vikaomelchenko** [comment]
![image](https://user-images.githubusercontent.com/38327021/39178187-c80f0cae-47b9-11e8-9baf-ddd817b7f924.png)

**Comment by vikaomelchenko** [comment]
Настя, кинь фото

**Comment by tushnitska** [comment]
![image](https://user-images.githubusercontent.com/38383436/39178249-e7ea653c-47b9-11e8-9c4b-154fe580cd83.png)

**Comment by Solomiya99** [comment]
Не забувайте про ціну, в межах розумного

**Comment by mariyasafyanyk** [comment]
і то що гостей багато буде
вистачить місця?

**Comment by systemofdown** [comment]
![image](https://user-images.githubusercontent.com/38244579/39178303-0615335c-47ba-11e8-962b-8e54f02c2bf4.png)

**Comment by vikaomelchenko** [comment]
Штука-ідеальний варіант
недорого і стиль прикольний

**Comment by mariyasafyanyk** [comment]
ооо
давайте

**Comment by systemofdown** [comment]
ок

**Comment by tushnitska** [comment]
Погоджуюсь

**Comment by Solomiya99** [comment]
Гаразд, я згідна
