### ISSUE TITLE
скласти меню

### ISSUE THREAD

**Issue by mariyasafyanyk** [Solomiya99/-sekta#2]
-українська кухня( борщ, пюре з відбивною, десерт)
-купити продукти
-приготувати

**Comment by systemofdown** [comment]
Може подивитися меню?

**Comment by vikaomelchenko** [comment]
я за щось легеньке

**Comment by mariyasafyanyk** [comment]
борщ треба!

**Comment by vikaomelchenko** [comment]
може якісь тортики?

**Comment by systemofdown** [comment]
ми забули про випивку. Хто що п'є?

**Comment by vikaomelchenko** [comment]
всім шампанське

**Comment by systemofdown** [comment]
![image](https://user-images.githubusercontent.com/38244579/39178476-7a068ac2-47ba-11e8-856f-ebb923da230e.png)

**Comment by tushnitska** [comment]
Хто дивився меню в "Штуці"? Киньте список, будь ласка

**Comment by Solomiya99** [comment]
треба так щоб всі були ситі і задоволені

**Comment by vikaomelchenko** [comment]
ням-ням

**Comment by mariyasafyanyk** [comment]
фраголінко

**Comment by Solomiya99** [comment]
http://www.shtuka.net.ua/menu/
Посилання на меню

**Comment by systemofdown** [comment]
Може там уже вибрати?

**Comment by vikaomelchenko** [comment]
давайте

**Comment by Solomiya99** [comment]
добре

**Comment by vikaomelchenko** [comment]
Бракує шампана!!!
