### ISSUE TITLE
Що подарувати іменинниці?

### ISSUE THREAD

**Issue by vikaomelchenko** [Solomiya99/-sekta#3]
-квитки на музичний фестиваль
-рамка
-power bank
-колонка

**Comment by systemofdown** [comment]
я за power bank

**Comment by systemofdown** [comment]
![image](https://user-images.githubusercontent.com/38244579/39178669-fe0cefa0-47ba-11e8-97a4-baa240031265.png)

**Comment by vikaomelchenko** [comment]
Соломія, що ти хочеш отримати?

**Comment by tushnitska** [comment]
на яку ціну розраховуємо?

**Comment by Solomiya99** [comment]
в мене вже є павербанк

**Comment by mariyasafyanyk** [comment]
![image](https://user-images.githubusercontent.com/38327045/39179039-f8a89a68-47bb-11e8-813c-c8551b854de2.png)

**Comment by vikaomelchenko** [comment]
відпадає

**Comment by mariyasafyanyk** [comment]
а таке?

**Comment by systemofdown** [comment]
2000?

**Comment by vikaomelchenko** [comment]
нічого так

**Comment by mariyasafyanyk** [comment]
30000

**Comment by mariyasafyanyk** [comment]
лишній 0

**Comment by vikaomelchenko** [comment]
може обговоримо подарунок без Соломії?

**Comment by systemofdown** [comment]
так цікавіще

**Comment by vikaomelchenko** [comment]
Соломія, закрий очі

**Comment by systemofdown** [comment]
Соломія нам ще щось порадить

**Comment by mariyasafyanyk** [comment]
![image](https://user-images.githubusercontent.com/38327045/39179163-4b8980ee-47bc-11e8-98c6-b662d450992e.png)

**Comment by mariyasafyanyk** [comment]
ще варіант

**Comment by systemofdown** [comment]
Соломія що хочеш?

**Comment by tushnitska** [comment]
це ж чоловіча

**Comment by vikaomelchenko** [comment]
лихі 90

**Comment by Solomiya99** [comment]
даруйте щось потрібне

**Comment by vikaomelchenko** [comment]
праску?

**Comment by systemofdown** [comment]
Хочеш Артема?

**Comment by tushnitska** [comment]
сковорідку?

**Comment by tushnitska** [comment]
Сковорідка і для самозахисту пригодиться!

**Comment by mariyasafyanyk** [comment]
![image](https://user-images.githubusercontent.com/38327045/39179239-7ca0aad6-47bc-11e8-8575-a480c5ea6ba2.png)

**Comment by vikaomelchenko** [comment]
це ти без макіяжу?

**Comment by systemofdown** [comment]
А тепер серйозно що?

**Comment by mariyasafyanyk** [comment]
давайте букет

**Comment by systemofdown** [comment]
Давайте

**Comment by tushnitska** [comment]
Давайте тур до Чехії на 2 дні

**Comment by vikaomelchenko** [comment]
оо, я за букет

**Comment by mariyasafyanyk** [comment]
![image](https://user-images.githubusercontent.com/38327045/39179316-ad2ae1a8-47bc-11e8-9c0c-bbfb62b02a7f.png)

**Comment by vikaomelchenko** [comment]
+

**Comment by vikaomelchenko** [comment]
тур-це дуже круто

**Comment by systemofdown** [comment]
Чехія і букет

**Comment by mariyasafyanyk** [comment]
тур - крута ідея

**Comment by vikaomelchenko** [comment]
все, вирішили
