### ISSUE TITLE
вибрати музику

### ISSUE THREAD

**Issue by systemofdown** [Solomiya99/-sekta#4]
Який тип музики?
Хто що хоче слухати?
Може замовити Діджея?

**Comment by vikaomelchenko** [comment]
в штуці грають музиканти живу музику

**Comment by tushnitska** [comment]
У "Штуці" можна замовити живу музику
Як вам  ідея?

**Comment by mariyasafyanyk** [comment]
давайте zalisko запросимо

**Comment by vikaomelchenko** [comment]
можна попросити зіграти якісь відомі пісні

**Comment by systemofdown** [comment]
я за

**Comment by mariyasafyanyk** [comment]
а він зі своїми музикантами прийде

**Comment by vikaomelchenko** [comment]
я за скрипічну музику

**Comment by Solomiya99** [comment]
наскільки я знаю там декілька піаністів, хто з них кращий
Віка ти часто відвідуєш, порадь

**Comment by mariyasafyanyk** [comment]
яка скрипічна????

**Comment by tushnitska** [comment]
гра на скрипці?

**Comment by vikaomelchenko** [comment]
Артем

**Comment by vikaomelchenko** [comment]
він дуже класно грає? і ще він симпатичний

**Comment by vikaomelchenko** [comment]
він дуже класно грає і ще він симпатичний

**Comment by tushnitska** [comment]
є фото?

**Comment by mariyasafyanyk** [comment]
прізвище?

**Comment by systemofdown** [comment]
це часом не він
![image](https://user-images.githubusercontent.com/38244579/39178902-93d26970-47bb-11e8-92d1-bd0e4d079805.png)

**Comment by vikaomelchenko** [comment]
http://www.shtuka.net.ua/news/boogie_shuffle_koncert_skrypkovogo_duetu_largo_21_4_2018/

**Comment by mariyasafyanyk** [comment]
підходить!!!

**Comment by vikaomelchenko** [comment]
або оце теж прикольне

**Comment by mariyasafyanyk** [comment]
він ще й співає?

**Comment by vikaomelchenko** [comment]
співає

**Comment by Solomiya99** [comment]
ми його беремо!!!

**Comment by mariyasafyanyk** [comment]
артемчик канає)))

**Comment by tushnitska** [comment]
Я за

**Comment by vikaomelchenko** [comment]
ладно, берем Артема
