### ISSUE TITLE
Скласти список гостей

### ISSUE THREAD

**Issue by tushnitska** [Solomiya99/-sekta#5]
Приблизно 15
Найближчі люди

**Comment by vikaomelchenko** [comment]
Юлю не запрошуєм!!!!

**Comment by mariyasafyanyk** [comment]
уляну теж!

**Comment by systemofdown** [comment]
Рома, Артем, Софа, Мішу

**Comment by mariyasafyanyk** [comment]
сашу може?

**Comment by vikaomelchenko** [comment]
а Саша?

**Comment by systemofdown** [comment]
Там Артем буде навіга тобі Саша?

**Comment by vikaomelchenko** [comment]
мені не треба

**Comment by vikaomelchenko** [comment]
Соломії треба

**Comment by systemofdown** [comment]
Ладно тоді Артем мій)

**Comment by mariyasafyanyk** [comment]
Саша
соломія
сергій 
віка
софія
настя
віка
вероніка
міша
рома
надя
іра
катя
бодя
град

**Comment by tushnitska** [comment]
1. Саша
2. Рома
3. Софія
4. Міша
5. Марічка
6. Віка
7. Соломія
8. Надя
9. Настя
10. Христя
11.  Іванка
12. Уляна

**Comment by systemofdown** [comment]
давайте де 15

**Comment by vikaomelchenko** [comment]
Уляну не запрошуєм!

**Comment by tushnitska** [comment]
точно, я забула

**Comment by tushnitska** [comment]
тоді 1ий список
